AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack for setting up the automated testing role."
Resources:
  CodeBuildAutomatedTestingRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/iam/automatedtest/"
      RoleName: codebuild-automated-test
  AutomatedTestParameterStore:
    Type: "AWS::IAM::Policy"
    DependsOn: CodeBuildAutomatedTestingRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "ssm:GetParameter"
            Resource: "arn:aws:ssm:*:*:parameter/iam/automated-test/*"
          -
            Effect: "Allow"
            Action:
              - "kms:Decrypt"
            Resource: "arn:aws:kms:us-west-2:320464205386:key/ef00015d-739b-456d-a92f-482712af4f32"
      PolicyName: get-automated-test-parameters
      Roles:
        -
          Ref: CodeBuildAutomatedTestingRole
  AutomatedTestCloudWatch:
    Type: "AWS::IAM::Policy"
    DependsOn: CodeBuildAutomatedTestingRole
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource: "arn:aws:logs:*:*:log-group:/aws/codebuild/*"
      PolicyName: put-cloudwatch-logs
      Roles:
        -
          Ref: CodeBuildAutomatedTestingRole
